version: "3.6"

services:
  web:
    image: ranckosolutions/todo-app-nginx:1.0-beta
    container_name: todo-app-nginx
    volumes:
      - ./:/usr/share/nginx/html:ro 
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, "-g", "daemon off;"]
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    ports:
      - "8090:80"
    depends_on:
      - database

#   database:
#     image: couchdb:2.3.1
#     container_name: todo-app-couchdb
#     environment:
#       - COUCHDB_USER=admin
#       - COUCHDB_PASSWORD=admin
#       - COUCHDB_PORT=5984
#     ports: # port mapping
#       - "5984:5984"
#     volumes: # volume mapping
#       - todo-app-data:/opt/couchdb/data # data directory
#       - todo-app-data:/var/lib/couchdb # data directory
#     command: [couchdb] # run couchdb

# volumes:
#   todo-app-data: