version: "3.6"

services:
  web:
    image: ranckosolutionsinc/todo-app-nginx:1.1-beta
    container_name: todo-app-nginx
    volumes:
      - ./:/usr/share/nginx/html:ro
    #   - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, "-g", "daemon off;"]
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
      - "8090:80"
    depends_on:
      - database

  database:
    image: couchdb:3.2
    container_name: todo-app-couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
      - COUCHDB_PORT=5984
    ports: # port mapping
      - "5984:5984"
    expose: 
      - 5984
    volumes: # volume mapping
      - todo-app-data:/opt/couchdb/data # data directory
      - todo-app-data:/var/lib/couchdb # data directory
      - ./couchdb/local.ini:/opt/couchdb/etc/local.ini  
    command: [couchdb] # run couchdb

volumes:
  todo-app-data:
